apiVersion: v1
kind: Namespace
metadata:
  name: nsinjector-controller

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsinjector-controller
  namespace: nsinjector-controller

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nsinjector-controller
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["blakelead.com"]
  resources: ["namespaceresourcesinjectors"]
  verbs: ["list", "get", "watch", "update"]
- apiGroups: ["rbac"]
  resources: ["*"]
  verbs: ["list", "get", "watch", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nsinjector-controller
subjects:
- kind: ServiceAccount
  name: nsinjector-controller
  namespace: nsinjector-controller
roleRef:
  kind: ClusterRole
  name: nsinjector-controller
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsinjector-controller
  namespace: nsinjector-controller
  labels:
    app: nsinjector-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nsinjector-controller
  template:
    metadata:
      labels:
        app: nsinjector-controller
    spec:
      serviceAccountName: nsinjector-controller
      containers:
      - name: nsinjector-controller
        image: blakelead/nsinjector-controller
        imagePullPolicy: Always